### ISSUE TITLE
DNS resolution failing

### ISSUE THREAD

**Issue by memolipd** [dperson/transmission#1]
Not sure if this is an image or tutum problem, but Im running this container on tutum, the container is running, the ports are open but nothing is downloading, in the container logs I see this:

    [transmission-2115c936-1] 2015-03-19T10:47:56.121542159Z 
    [transmission-2115c936-1] 2015-03-19T10:47:56.121542159Z gzip: stdin: unexpected end of file
    [transmission-2115c936-1] 2015-03-19T10:47:56.156678052Z Couldn't open "/dev/stdout": Permission denied
    [transmission-2115c936-1] 2015-03-19T10:48:45.405161151Z [2015-03-19 10:48:45.404 UTC] DHT dht.transmissionbt.com:6881: Temporary failure in name resolution (tr-dht.c:126)
    [transmission-2115c936-1] 2015-03-19T10:49:30.405287854Z [2015-03-19 10:49:30.405 UTC] DHT dht.transmissionbt.com:6881: Temporary failure in name resolution (tr-dht.c:126)
    [transmission-2115c936-1] 2015-03-19T10:50:27.405018643Z [2015-03-19 10:50:27.404 UTC] DHT dht.transmissionbt.com:6881: Temporary failure in name resolution (tr-dht.c:126)
    [transmission-2115c936-1] 2015-03-19T10:50:51.916751880Z 
    [transmission-2115c936-1] 2015-03-19T10:50:51.916798457Z gzip: stdin: unexpected end of file
    [transmission-2115c936-1] 2015-03-19T10:50:51.934206395Z Couldn't open "/dev/stdout": Permission denied
    [transmission-2115c936-1] 2015-03-19T10:51:23.186815564Z [2015-03-19 10:51:23.186 UTC] DHT dht.transmissionbt.com:6881: Temporary failure in name resolution (tr-dht.c:126)
    [transmission-2115c936-1] 2015-03-19T10:51:53.186839552Z [2015-03-19 10:51:53.186 UTC] DHT dht.transmissionbt.com:6881: Temporary failure in name resolution (tr-dht.c:126)
    [transmission-2115c936-1] 2015-03-19T10:52:42.186217245Z [2015-03-19 10:52:42.186 UTC] DHT dht.transmissionbt.com:6881: Temporary failure in name resolution (tr-dht.c:126)

**Comment by dperson** [comment]
I've created a new build which will get rid of the error about /dev/stdout.

As for DNS on tutum, I've no experience with them as a PaaS (Platform as a Service) provider.

Do they let you 'docker exec -it <container_name> bash' connect? If so you can interactively try to troubleshoot it. My first suggestion is to try manually assigning the Google DNS servers either at run (--dns 8.8.4.4 --dns 8.8.8.8), or when you exec in, modify the /etc/resolv.conf and restart the container.

Hope this helps.

**Comment by memolipd** [comment]
Thanks! I think you're right, my containers can't see the outside world, I'll get onto tutum about this!
