### ISSUE TITLE
settings.json is overwritten when starting container

### ISSUE THREAD

**Issue by SureNotXim** [dperson/transmission#12]
Hi,

I'm trying to bind a custom settings.json to the container, but whenever I start the container my settings.json gets overwritten. Is there a way to change this behavior?

What I do:
$ sudo docker run --name transmission -p 9091:9091 -v /etc/transmission-daemon:/var/lib/transmission-daemon/.config/transmission-daemon/ -d dperson/transmission
$ sudo docker stop transmission
$ sudo vim /etc/transmission-daemon/settings.json # Modifying stuff, password, username...
$ sudo docker start transmission
$ # Wait 10 sec
$ sudo vim /etc/transmission-daemon/settings.json # My stuff is not here anymore

I use this image from a chef recipe and I can't provide a clear password as environment variable, so I'm stuck with using a custom settings.json with secure password

**Comment by Aestek** [comment]
This might help you https://github.com/dperson/transmission/pull/11

**Comment by Aestek** [comment]
Also, the settings file managed by the image is `/var/lib/transmission-daemon/info/settings.json`

**Comment by SureNotXim** [comment]
Blows my mind

$ find / -name settings.json
/etc/transmission-daemon/settings.json
/var/lib/transmission-daemon/.config/transmission-daemon/settings.json

$ find /var/lib/transmission-daemon/info/ -name settings.json
/var/lib/transmission-daemon/info/settings.json

**Comment by SureNotXim** [comment]
Oh does it mean I can give a secured password as environment variable? Do you know how to manually generate it? It would solve my problem.

**Comment by Aestek** [comment]
Dunno if the hash is salted, try http://superuser.com/questions/113649/how-do-you-set-a-password-for-transmission-daemon-the-bittorrent-client-server

**Comment by SureNotXim** [comment]
I tried with /var/lib/transmission-daemon/info/settings.json, same issue, I lose all changes on docker start. 

According to https://github.com/dperson/transmission/issues/3 It's not supposed to behave that way

**Comment by Aestek** [comment]
Username and password are passed via command line opts. Transmission stores them in the config file on startup.

**Comment by dperson** [comment]
In the base debian package, '/var/lib/transmission-daemon/info' is a symlink to '/var/lib/transmission-daemon/.config/transmission-daemon'. Which explains the results you were seeing from find.

AFAIK (As Far As I Know), transmission is looking for the user / passwd as plain text. That's how I'm using it (which is working). In the settings.json however, the passwd is hashed. Maybe, it's deciding your config file is corrupt?

I'm personally using a local path for all of /var/lib/transmission-daemon, and a separate one for downloads. This preserves incomplete downloads. I've had no issues with my config being overwritten. IE:

`docker run -it --name bit -v /srv/transmission:/var/lib/transmission-daemon -v <my_path>:/var/lib/transmission-daemon/downloads -d dperson/transmission`

Please let me know if this helps you.

**Comment by dperson** [comment]
I've just submitted a update that cleans up debian's mess with `.config/transmission-daemon` vs `info`. Now there is only `info`. There's also a note in the `README.md` about the file locations. Hopefully this will improve the situation for you and others.

**Comment by SureNotXim** [comment]
Hi :) Thanks for the hint for the symlink.

For the file rewrite, can you try the following?
> docker exec -it transmission-container bash
> cat /var/lib/transmission-daemon/info/settings.json
> exit
> docker stop -it transmission-container
> docker start -it transmission-container
> docker exec -it transmission-container bash
> cat /var/lib/transmission-daemon/info/settings.json

You should (hopefully) see that the password's hash is different, my wild guess is that this is due to the salt / key they use to be different, and this being due to the way transmission is started from transmission.sh.

I think the solution would be to simply call `/etc/init.d/transmission-daemon start` if settings.json already exist

**Comment by SureNotXim** [comment]
This would also play better with docker principle that a container should mostly be immutable once created :)

**Comment by dperson** [comment]
Yes, I'm seeing the updated hashes as well.

If it was just configuration command line arguments, then I would agree. But I'm also redirecting logs, setting the configuration/downloads/incomplete directories, and having it run in the foreground (the container will otherwise exit).

I'm only modifying files inside the volume created for the daemon (it's also where in progress and completed downloads go). Without it being able to modify those it would be pretty useless. =) And that is actually one reason that I don't use the old style init scripts, they use more tracking files in `/var`, `/run`, etc. Also as mentioned we don't really want it in the background...

At some point the RedHat folks are working on systemd for launching things inside the containers, but it's still a ways out from release. I'd much rather write unit files to handle launching daemons.

**Comment by SureNotXim** [comment]
I fixed the issue by simply removing username and password form the command line.

If you want to fix it, IMO the correct behavior would be:
* If username / password are provided as environment variables, pass them as command line args (not sure if the constant "rewrite" of password by transmission would have any practical impacts, if yes consider writing them in settings.json instead)
* If username / password are not provided as environment variables, do not pass them and stick to the default transmission behavior (which is IMO what the user expects):
 * transmission will put the default to transmission/transmission instead of admin/admin
 * possibility to provide them in the configuration file as documented by transmission

**Comment by dperson** [comment]
One thing that I discovered was that `transmission-daemon` writes it's configuration file on exit. If I tried to make changes while it was running I could, but it would overwrite them on shutdown. This could well be the behavior that you were seeing that triggered this bug report.

As far as your last request, from what I've [read](http://superuser.com/questions/113649/how-do-you-set-a-password-for-transmission-daemon-the-bittorrent-client-server) (and sort of remember from when I created this container), if no password has been set, it will assign a random one and spit it out in it's logs (in this case the docker log). I wanted to provide a simple default for people to use/try easily. With that also a simple way to provide more secure user/passwd. This was the best compromise that I could find

**Comment by SureNotXim** [comment]
Yes I am aware of this behavior from transmission-daemon, but this is not related. You can make sure by simply executing the following:

> sudo docker run -d dperson/transmission --name transmission-test -v /var/local/transmission/:/var/lib/transmission-daemon/info
> cat /var/local/transmission/settings.json
> sudo docker stop transmission-test
> vim /var/local/transmission/settings.json #change username and/or password
> sudo docker start transmission-container
> #Wait 10 seconds, the container is starting... ;)
> cat /var/local/transmission/settings.json

The username and password will have changed. The reason is that your startup script in transmission.sh overrides this by using admin/admin if no environment variable is set. You can also try to set environment variables, and you will notice that from one execution to another, the password will change even with the same environment variables.

There are two problems:
* Impossible to set username/password through settings.json
 * If no env.var are set, the container will always default to admin/admin even if settings.json says otherwise
 * If env.var are set, well, the container will use those as username and password
* The passwords changes every time the container is started. I'm not sure if there are any impacts, but it's always nice to avoid it.

You can try the same with surenot/transmission and it should work (hopefully :D)

> sudo docker run -d dperson/transmission --name transmission-test -v /var/local/transmission/:/var/lib/transmission-daemon/info
> #Same commands as earlier...

The only thing I change is that I don't provide any defaults if environment variables are not set. In that case, transmission should use settings.json if available, otherwise create it with defaults to transmission/transmission.

**Comment by SureNotXim** [comment]
Actually you might be right for the default username/password, I can't find anything on the doc https://trac.transmissionbt.com/wiki/EditConfigFiles. Dunno why I ended up with transmission/transmission.

**Comment by dperson** [comment]
I understand what you're saying, what's happening, and what you want. I also appreciate the time you've put in to look at this, and to clearly state the issue.

However as you said, I'm not sure how to cover the "common" use case (as it seems to me, and described previously), and what you want (you can't set the environment variables but want to set the password). I just don't know how to cut this Gordian Knot.

If I come up with anything, I'll update the container and this bug report.

**Comment by gmolveau** [comment]
Hi, sorry to update this issue, I just wanted to know if you came up with a patch for this behaviour ?
Thank you for your work :)

**Comment by dperson** [comment]
No, the status remains as stated above.
