### ISSUE TITLE
Settings environment variable translation corrupts file

### ISSUE THREAD

**Issue by optilude** [dperson/transmission#13]
For example:

$ docker run --rm --name transmission --net=container:vpn -e TRUSER=admin -e TRPASSWD=admin -e TR_UMASK=0 dperson/transmission

I get:

[2016-01-11 21:21:45.764 UTC] JSON parse failed in /var/lib/transmission-daemon/info/settings.json at pos 689: STRAY_TOKEN -- remaining text ""umask": "0",
}
"

and the container exits.

I've tried various versions of the TR_UMASK variable, with and without quotes etc and it has the same result, as does changing a string variable like "peer-congestion-algorithm".

**Comment by dperson** [comment]
Thank you for finding and reporting this bug. It's fixed now in my testing.
