### ISSUE TITLE
Can't connect to port 9091 on host

### ISSUE THREAD

**Issue by henry74** [dperson/transmission#2]
Hey David,

Thanks for putting together these docker containers.  Just tried linking this container with the openvpn-client container, but really confirm it's running correctly.  Used this command per your instructions:
```
docker run --name transmission -p 9091:9091 -v /home/guest/downloads:/var/lib/transmission-daemon/downloads --net=container:openvpn -d dperson/transmission
```

Looking at the logs:
```
Couldn't open "/dev/stdout": Permission denied
[2015-07-08 19:40:54.003 UTC] blocklist skipped invalid address at line 1 (blocklist.c:365)
[2015-07-08 19:40:54.003 UTC] blocklist skipped invalid address at line 2 (blocklist.c:365)
[2015-07-08 19:40:54.004 UTC] UDP Failed to set receive buffer: requested 4194304, got 425984 (tr-udp.c:78)
[2015-07-08 19:40:54.004 UTC] UDP Failed to set send buffer: requested 1048576, got 425984 (tr-udp.c:89)
```

Can't seem to connect to transmission running on port 9091 on the host even when I try it locally on the host machine. Thoughts?

**Comment by henry74** [comment]
Looks like the primary culprit is the --net=container:openvpn parameter.  Without, it works fine.  How do you get it to play nice and use the openvpn-client container through the docker run options?

**Comment by dperson** [comment]
Hey Henry,

The errors are normal, and nothing to worry about. Docker places some
limits on the processes run in containers.

What path are you trying to connect to? I just realized it's not in the
README that you have to connect to `http://<name_or_IP>:9091/transmission/web`,
if that's your issue, I'll add it to the docs so it doesn't trip up others
as well.

Thanks for reporting it.

-- 
David P.

**Comment by henry74** [comment]
With the --net=container:openvpn I'm unable to reach the transmission daemon:
```
sudo iptables -t nat -L -n
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        0.0.0.0/0           

Chain DOCKER (2 references)
target     prot opt source               destination
```
Without the --net parameter, it's reachable:
```
sudo iptables -t nat -L -n
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        0.0.0.0/0           
MASQUERADE  tcp  --  172.17.0.25          172.17.0.25          tcp dpt:51413
MASQUERADE  udp  --  172.17.0.25          172.17.0.25          udp dpt:51413
MASQUERADE  tcp  --  172.17.0.25          172.17.0.25          tcp dpt:9091

Chain DOCKER (2 references)
target     prot opt source               destination         
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:32768 to:172.17.0.25:51413
DNAT       udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:32768 to:172.17.0.25:51413
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:9091 to:172.17.0.25:9091
```

**Comment by dperson** [comment]
I am running it using the `--net=container:openvpn` option.

The only other difference that I can think of is that I'm running
dperson/nginx as a reverse proxy in front of it (`--link openvpn:bit` to
connect the web server to transmission and  `-w "
http://bit:9091/transmission;/transmission"` as an argument to the nginx
startup script to configure the proxying of /transmission to the
transmission container).

But it shouldn't be needed to get to the transmission web interface.

I'm at work right now, when I'm back on the local network with my home
server,  I'll test creating another transmission and accessing it directly.

What Linux distro / kernel / docker version are you running (return the
output of: `cat /etc/*release; uname -a; docker version` if you would)?

Thanks.

-- 
David P.

**Comment by henry74** [comment]
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
Linux server 4.1.0-x86_64 SMP Mon Jun 22 10:39:23 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
Client version: 1.7.0-dev
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 5e06332
OS/Arch (client): linux/amd64
Server version: 1.7.0-dev
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 5e06332
OS/Arch (server): linux/amd64
```

**Comment by dperson** [comment]
Well it definitely looks like you're up to date on your kernel / docker.
That shouldn't be the problem...

-- 
David P.

**Comment by henry74** [comment]
Any luck? :-)

**Comment by dperson** [comment]
Sorry, too much going on last night, I didn't get a chance. I'll try to do
it tonight.

-- 
David P.

**Comment by dperson** [comment]
Sorry for the long delay. I did finally get around to testing it, and could reproduce your issue. When using another container's network, the `-p` option is broken in docker. I'll update the README.md to reflect that you'll have to run it proxied behind a web server.

**Comment by henry74** [comment]
Can you provide an example on how to run it using a proxied web server?

**Comment by dperson** [comment]
Sigh, sorry I meant to add it to the README.md right after I replied. It has been added now (at least the build is pending). It's on github and will be on the docker page shortly. Thanks.

**Comment by henry74** [comment]
Small error in the documentation: The openvpn container is named vpn but it's linked to the bit container as --net=container:openvpn instead of --net=container:vpn

**Comment by dperson** [comment]
Thank you, I'm glad you caught that. I just checked in the fixed README.md.

**Comment by henry74** [comment]
Still a reference to openvpn when linking to the container using the net
parameter

**Comment by dperson** [comment]
Sigh, my bad. Thank you.

-- 
David P.
