### ISSUE TITLE
Rookie Question

### ISSUE THREAD

**Issue by rlopez1986** [dperson/transmission#21]
So i am trying to change the GROUPID to 775. When i run my command" transmission.sh GROUPID 775" it say command not found. I know that the way I structure my command that its the wrong way.  And I have try different ways to write my command.  So I was wondering if you could give me some examples in how to write my command. My container is QNAP. Like I said I'm rookie at the terminal. Any help will be appreciated. Thank You.

**Comment by dperson** [comment]
That's not how you set an environment variable. Try the following:

`sudo docker run -it --name transmission -e GROUPID=775 -d dperson/transmission`
