### ISSUE TITLE
Provide link to local transmission web

### ISSUE THREAD

**Issue by brianlow** [dperson/transmission#23]
Under "How to use this image" would be good to mention "Browse to http://localhost/transmission/web/". 

Super minor, but took a bit of searching to figure out the url. Also the trailing forward slash is important - otherwise you get a 409 code back.

Thanks for the image

**Comment by dperson** [comment]
I can point people to the `/transmission/web/` URI but it's quite possible they won't be running it on their local machine, so `localhost` wouldn't work for them. Thanks for the suggestion.
