### ISSUE TITLE
Permission denied on settings.json

### ISSUE THREAD

**Issue by linkdata** [dperson/transmission#28]
You need to set permissions on `/etc/transmission-daemon/settings.json` so that the `USERID` and `GROUPID` provided can read it, or transmission will fail with a "Permission denied" error trying to read it.

> `transmission.sh`

```
chown -Rh debian-transmission. /etc/transmission-daemon 2>&1 | grep -iv 'Read-only' || :
```

**Comment by dperson** [comment]
Thanks for the report, it should be fixed now.
