### ISSUE TITLE
transmission complains about some sysctl values

### ISSUE THREAD

**Issue by florid2** [dperson/transmission#29]
The log shows some UDP errors. 

UDP Failed to set receive buffer: requested 4194304, got 425984 (tr-udp.c:84)
UDP Please add the line &quot;net.core.rmem_max = 4194304&quot; to /etc/sysctl.conf (tr-udp.c:89)
UDP Failed to set send buffer: requested 1048576, got 425984 (tr-udp.c:95)
UDP Please add the line &quot;net.core.wmem_max = 1048576&quot; to /etc/sysctl.conf (tr-udp.c:100)

Not if some needs to tune the sysctl in docker or host system. Please advise. Thanks.

**Comment by dperson** [comment]
It will still work without them being set. Yes, containers do share the kernel with the host, so if you want to set them, you'll have to do so there.

**Comment by florid2** [comment]
Thank you for your promptly response. 
However, after I modified the host system file, the docker container still complains the same messages. 
I know transmission still works. But I just want to sort out this error. Anything can be set in docker variables environment?

**Comment by dperson** [comment]
I missed it in the release announcements but at least some sysctl settings are now namespaced. If you add `--sysctl <setting>` to your run line (IE, `--sysctl net.core.rmem_max = 4194304`). You can also set them in [compose files](https://docs.docker.com/compose/compose-file/#sysctls).

**Comment by tYYGH** [comment]
Hi! I have the same problem. May I know which sysctl values must be set to avoid this error, or which privileges must be granted? I currently run transmission in a systemd-nspawn container, with this systemd drop-in:

```
[Service]
CapabilityBoundingSet=CAP_AUDIT_WRITE CAP_LEASE CAP_SYS_CHROOT CAP_SYS_NICE
PrivateDevices=yes
PrivateTmp=yes
ProtectHome=yes
ProtectSystem=full
LimitNOFILE=4096
```

**Comment by dperson** [comment]
The values to set are right in the error messages. Those values are still not namespaced, so can't be applied to just the one container. I can confirm that for me setting them on the host that I don't get the error messages in the container. However I don't bother.
