### ISSUE TITLE
Config settings not saved

### ISSUE THREAD

**Issue by gtaking112** [dperson/transmission#3]
Hi, I'm running Docker on a Synology DS214play and when I create a container from the image and run it, works perfectly. However, upon stopping the container and restarting, all config settings and loaded torrents have been lost. Is this a problem with the Transmission image or Synology's implementation of Docker? Thanks

**Comment by dperson** [comment]
They shouldn't be lost on a stop and start, unless it removes the container
and spawns a new one... can you specify a volume from the local file
system? I have no idea how it's done on synology, but on the docker command
line `-v </local/path>:/var/lib/transmission-daemon` will mount
`</local/path>` (a local file system path, chosen by you, `<>` just
indicate what to replace) into the location where all settings / torrents /
in progress files are stored. As long as that's set it should store state
outside of the container.

But first, there are files created by the package installation in that
directory, so before you do that, run this docker command: `docker cp
<name_of_running_transmission_container>:/var/lib/transmission-daemon
</local/path>`

Hope this helps.

-- 
David P.
