### ISSUE TITLE
Why not alpine?

### ISSUE THREAD

**Issue by lucaszanella** [dperson/transmission#31]
Hey, very nice image I see, but why is this so complicated? Shouldn't it be better to use something like alpine? I see a lot of commands in the dockerfile but I don't know what all this is doing. What are the challenges that you had while writing this image? Normally when I write mine I see error and them I install the missing things, but in debian I remember to just do apk-get install transmission-daemon or something like that

**Comment by dperson** [comment]
The "complications" are setting up the initial configuration and getting files/directories ready for it to run. I may rewrite my images to use alpine at some point, but haven't had a strong motivation to do so. Some of the software I have images for doesn't have versions for alpine. Debian isn't that large an image in the first place, so there's not that much bloat.

**Comment by antoineco** [comment]
From what I see it would be reasonably easy to rebase this image on Alpine. The relevant package is here: https://pkgs.alpinelinux.org/packages?name=transmission-daemon

Would you accept a PR?
