### ISSUE TITLE
After added -v option, docker wont start

### ISSUE THREAD

**Issue by netsys-it** [dperson/transmission#35]
That works
docker run -it --name transmission -p 9091:9091 -d transmission 

that doesnt works:
docker run -it --name transmission -p 9091:9091 -d transmission -v /shared/torrents/:/var/lib/transmission-daemon

am i doing something wrong?

**Comment by dperson** [comment]
Sorry for the slow reply, I was out of town on vacation.

When you replace the contents of `/var/lib/transmission-daemon` with what I assume is an empty directory, it's wiping out configs and expected directories. If you run the following, it should work to get things ready for you:
```
docker run -it --name transmission -p 9091:9091 -d dperson/transmission
docker cp transmission:/var/lib/transmission-daemon/ /shared/torrents/
docker rm -f transmission
docker run -it --name transmission -p 9091:9091 -d dperson/transmission -v /shared/torrents/:/var/lib/transmission-daemon
```
