### ISSUE TITLE
Help a newbie

### ISSUE THREAD

**Issue by mkorablin** [dperson/transmission#36]
I think I'm missing something. I'm trying to start this container on Synology NAS, but get the following in the logs:
```
su: System error | stdout
awk: cannot open /var/lib/transmission-daemon/info/settings.json (No such file or directory)
```

I'm mapping `/var/lib/transmission-daemon` to a local folder on a NAS. It seems like `settings.json` should be generated, judging by `dockerfile` but it's not.

What am I missing?

**Comment by beshkenadze** [comment]
@mkorablin hey, do you specifying a folder to mount it?

**Comment by mkorablin** [comment]
Yes, in container configuration, I mapping a local folder to `/var/lib/transmission-daemon`.

**Comment by dperson** [comment]
When you mount over `/var/lib/transmission-daemon` you are putting an empty directory in place of the contents created by the `Dockerfile`. Please see the additional *Complex configuration* note that I've added to the `README.md`.
