### ISSUE TITLE
Enviroment Variables TR_WATCH_DIR and TR_WATCH_DIR_ENABLE

### ISSUE THREAD

**Issue by erauzkin** [dperson/transmission#43]
The variables TR_WATCH_DIR_ENABLE and TR_WATCH_DIR correctly modify the settings.json file, but torrents are not added to tranmission.

Thanks

**Comment by dperson** [comment]
That sounds like a transmission bug... or packing / build bug at the OS level. I'd recommend reporting it to the Alpine bug tracker. Sorry but I don't manage it, just make use of what is in the repo.
