### ISSUE TITLE
add unrar to image

### ISSUE THREAD

**Issue by vdpollm** [dperson/transmission#44]
Hi, this is more of a feature request than an issue.

would it be possible to add unrar? i would like to run a script to automatically unrar files, instead of having to do this manually.

please let me know

regards
Marc

**Comment by dperson** [comment]
Containers are supposed to be single purpose and small. Unless there are more people that ask for this feature as well, I'm going to pass.

I'll close the issue, but will get alerts if there are additional comments asking for it to be added. Which could change my mind.

**Comment by niXta1** [comment]
I agree that unzip/unrar is in the scope of a transmission container.

**Comment by karan** [comment]
I would really like unrar built-in as well, and sane permission management!

**Comment by dperson** [comment]
The management / extraction of the downloaded files isn't something that the web interface allows, and is beyond what transmission manages, so is beyond the scope of the container, IMHO.
