### ISSUE TITLE
GROUPID only works with existing groups

### ISSUE THREAD

**Issue by christer** [dperson/transmission#5]
USERID changes the UID of the user to the given number but GROUPID changes
the default group of the user to the given group.

    [[ "${USERID:-""}" =~ ^[0-9]+$ ]] && usermod -u $USERID debian-transmission
    [[ "${GROUPID:-""}" =~ ^[0-9]+$ ]] && usermod -g $GROUPID debian-transmission

I think the idea is to have GROUPID to change the GID of the debian-transmission group to the given number.

    [[ "${GROUPID:-""}" =~ ^[0-9]+$ ]] && groupmod -g $GROUPID debian-transmission

**Comment by dperson** [comment]
That is literally what I meant to do, but just changed the Variable and not the command after coping the line and pasting.</facepalm>

It should be fixed now, and thank you.
