### ISSUE TITLE
Mounting /var/lib/transmission-daemon/info results in missing settings

### ISSUE THREAD

**Issue by netvl** [dperson/transmission#50]
Currently Dockerfile generates settings directly into the container image. If afterwards the container has its `/var/lib/transmission-daemon/info` directory mounted to the host, the settings file it contains disappears from the container point of view, resulting in invalid settings and the entrypoint script not finding a settings file to update.

Maybe it would make sense to move the initial config generation to the entrypoint script as well? This would make it much easier to work with configuration, especially in ephemeral setups like docker-compose.

**Comment by dperson** [comment]
There's a whole directory tree in there, as well as settings. I'll think about it but I'm not really sold on the idea.

**Comment by netvl** [comment]
Not sure I got the point of the
> There's a whole directory tree in there, as well as settings

statement. My point is, at the moment a considerable part of configuration is generated at the image build time, and the start script expects this configuration to exist in the image. If the `/info` directory or any of its parent directories is mounted as a volume, then the start script fails to actually start transmission. The main problem here is that it makes working with "ephemeral" containers harder: if transmission is launched with, say, `docker-compose`, and then for whatever reason the compose graph is rebuilt (e.g. another container is added, or something like that), the container gets recreated, and all data in the `/info` directory gets lost.

**Comment by dperson** [comment]
For whatever reason you're deleting the settings, the startup script will recreate the directories and a default configuration now.
