### ISSUE TITLE
Permission error when executing done script

### ISSUE THREAD

**Issue by karan** [dperson/transmission#51]
I'm trying to run unrar once a download is finished.

I've set `USERID` and `GROUPID` to `1000` when running the container. I've set the correct value in `settings.json`:

```
    "script-torrent-done-enabled": true,
    "script-torrent-done-filename": "/var/lib/transmission-daemon/info/unrar.sh",
```

The script looks like this:

```
#!/usr/bin/env bash

touch unrar.log
echo "unrar $TR_TORRENT_DIR/$TR_TORRENT_NAME/" >> unrar.log
/usr/bin/unrar x "$TR_TORRENT_DIR/$TR_TORRENT_NAME/*.rar" 2>> unrar.log
```

Now, when it runs, I get permission error:

```
touch: unrar.log: Permission denied
/var/lib/transmission-daemon/info/unrar.sh: line 10: unrar.log: Permission denied
/var/lib/transmission-daemon/info/unrar.sh: line 11: unrar.log: Permission denied
```

The script should run as user `transmission`, and I have confirmed that by doing `whoami` in the script.

Inspecting the container, looks like all the files are owned by `transmission:transmission`:

```
drwxr-xr-x    7 transmis transmis     12288 Jan  9 20:51 Downloads
drwxrwxr-x    2 transmis transmis      4096 Aug 30 12:16 downloads
drwxr-xr-x    2 transmis transmis      4096 Jul  1  2018 incomplete
drwxrwxr-x    5 transmis transmis      4096 Jan 29 20:39 info
-rw-r--r--    1 transmis transmis         9 Jan 27 19:49 unrar.log
```

So, my script should have permissions on all the files. Why does it not? Is there a way to run it as root (inside the container)?

**Comment by karan** [comment]
To be clear, I think it's the access to the `unrar.log` file that seem to be the problem, or any other file that the script creates.

**Comment by dperson** [comment]
I make sure that the ownership of the `/var/lib/transmission-daemon` directory is the transmission user and group. I don't know where your scripts current directory is however. Try adding a line to cd to the directory where you want the log file to be before running the `touch` command in your script.
