### ISSUE TITLE
message level returns to 2

### ISSUE THREAD

**Issue by djslmft** [dperson/transmission#52]
Hello,

I'm using your docker image as a "Rock-on" on a Rockstor fueled home NAS. I tried to change in the settings.json file the message-level to 1, but every time i restart the container it returns to 2
Is there any option to get this done? it writes a lot of irrelevant info to my log and i don't see the important data

Thanks in advance

**Comment by dperson** [comment]
I'm not sure how you're editing the config. One word of warning, every time the daemon shuts down, it overwrites it config with the running configuration. I'm not setting the `message-level` anywhere though.

**Comment by djslmft** [comment]
Thanks for the reply, I edit the config with stopped container, that's why I asked you

**Comment by djslmft** [comment]
FYI: the startup script in the container sets the log level to error, i changed it, to info, now it's solved...

**Comment by dperson** [comment]
Ah, sorry I missed that.
