### ISSUE TITLE
Torrents do not start automatically when host reboots

### ISSUE THREAD

**Issue by duel007** [dperson/transmission#6]
Hi,

Not sure if this is expected behavior or not. The container itself restarts as I have it set with restart always. However the torrents themselves are always in the stopped, completed stage, when you'd generally expect them to be in the state they were left in before reboot.

**Comment by dperson** [comment]
I think that I found the cause, either that or it's going to try to launch everything on a restart... sigh. I don't have any active torrents ATM (At The Moment) so I'm not sure.

It's in place for now, I may revert it if it doesn't resume statefully, but just everything.

**Comment by duel007** [comment]
Thank you for the timely response. I'll update my container and see how it
works.

On Mon, Nov 9, 2015 at 7:21 AM, David Personette <notifications@github.com>
wrote:

> I think that I found the cause, either that or it's going to try to launch
> everything on a restart... sigh. I don't have any active torrents ATM (At
> The Moment) so I'm not sure.
>
> It's in place for now, I may revert it if it doesn't resume statefully,
> but just everything.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dperson/transmission/issues/6#issuecomment-155059569>.
>



-- 
Matt Ware
712-310-6217
mattj.ware@gmail.com

**Comment by duel007** [comment]
Excellent, this does work. Thank you very much.

On Mon, Nov 9, 2015 at 9:36 AM, Matt Ware <mattj.ware@gmail.com> wrote:

> Thank you for the timely response. I'll update my container and see how it
> works.
>
> On Mon, Nov 9, 2015 at 7:21 AM, David Personette <notifications@github.com
> > wrote:
>
>> I think that I found the cause, either that or it's going to try to
>> launch everything on a restart... sigh. I don't have any active torrents
>> ATM (At The Moment) so I'm not sure.
>>
>> It's in place for now, I may revert it if it doesn't resume statefully,
>> but just everything.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/dperson/transmission/issues/6#issuecomment-155059569>
>> .
>>
>
>
>
> --
> Matt Ware
> 712-310-6217
> mattj.ware@gmail.com
>
>


-- 
Matt Ware
712-310-6217
mattj.ware@gmail.com
