### ISSUE TITLE
Ability to provide a config file in a different volume to the downloads

### ISSUE THREAD

**Issue by nickw444** [dperson/transmission#9]
It would be useful to allow users to provide a config file outside of the downloads volume, and possibly different volumes for complete/incomplete. 

This is something that might be worthwhile documenting

**Comment by dperson** [comment]
Users can always do so with the '-v' option to docker run.

**Comment by nickw444** [comment]
True, thanks. Just might be something worth having documented somewhere (ie, the path for configuration) to make it easier to for someone outside to quickly know the path to mount as a volume.

**Comment by dperson** [comment]
I'd actually already added in a note to the `README.md` after your earlier question. =)

\*sigh\* if I was building it right now, I'd probably move whole thing from `/var/lib/transmission-daemon` (where the package put things by default) to `/app` or something similar. But it would likely break things for people if I change it now.

**Comment by nickw444** [comment]
My bad, I didn't bother to check again. Thanks for that :smile:
